### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by pybnafp** [neu-szy/dual-guidance_LDCT_SR#1]
能分享下数剧集下载链接吗？谢谢！

**Comment by neu-szy** [comment]
论文中的数据可在下方链接下载：
链接：https://pan.baidu.com/s/1EZDlZwGO4IxRGERtmiR--Q 
提取码：edtg 
原始数据可在下方链接下载：
3dircadb: https://www.ircad.fr/research/data-sets/liver-segmentation-3d-ircadb-01/
pancreas: https://www.kenhub.com/en/library/anatomy/the-pancreas

**Comment by pybnafp** [comment]
谢谢，真是非常感谢！！
















在 2023-10-18 13:53:19，"neu-szy" ***@***.***> 写道：

论文中的数据可在下方链接下载：
链接：https://pan.baidu.com/s/1EZDlZwGO4IxRGERtmiR--Q
提取码：edtg
原始数据可在下方链接下载：
3dircadb: https://www.ircad.fr/research/data-sets/liver-segmentation-3d-ircadb-01/
pancreas: https://www.kenhub.com/en/library/anatomy/the-pancreas
